version: "3.7"


services:
  website:
    build: "."
    image: "zarve1/quick_website:website"
    hostname: "0.0.0.0"

  nginx:
    build: "./nginx"
    image: "zarve1/quick_website:nginx"
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - website

networks:
  default:
    name: backend-network
    driver: bridge